name: task_flow
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  go_router: ^14.6.2
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
